from __future__ import annotations

import os
import shutil
from pathlib import Path

from acpw.types import InstallResponse

MARKER = "# acpw bash completion"
COMPLETION_DIR = Path.home() / ".local" / "share" / "bash-completion" / "completions"


def _completion_script() -> str:
    return """# acpw — generated by `acpw install`
_acpw_completion() {
  local IFS=$'\\n'
  local completions
  completions="$(COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD="${COMP_CWORD}" _ACPW_COMPLETE=complete-bash acpw 2>/dev/null)"
  if test -n "${completions}"; then
    COMPREPLY=( $(compgen -W "${completions}" -- "${COMP_WORDS[COMP_CWORD]}") )
  fi
}
complete -o default -F _acpw_completion acpw
"""


def install_shell() -> InstallResponse:
    notes: list[str] = []
    acpw = shutil.which("acpw")
    if not acpw:
        notes.append("acpw not on PATH; run: uv tool install --editable <this-repo>")
    COMPLETION_DIR.mkdir(parents=True, exist_ok=True)
    completion_path = COMPLETION_DIR / "acpw"
    completion_path.write_text(_completion_script(), encoding="utf-8")
    bashrc = Path.home() / ".bashrc"
    updated = False
    line = f'[ -f "{completion_path}" ] && . "{completion_path}"'
    existing = bashrc.read_text(encoding="utf-8") if bashrc.exists() else ""
    if MARKER not in existing:
        with bashrc.open("a", encoding="utf-8") as fh:
            fh.write(f"\n{MARKER}\n{line}\n")
        updated = True
        notes.append(f"appended {MARKER} to ~/.bashrc; open a new shell")
    local_bin = str(Path.home() / ".local" / "bin")
    path = os.environ.get("PATH", "")
    if local_bin not in path.split(":"):
        notes.append(f"add {local_bin} to PATH")
    return InstallResponse(acpw=acpw, completion=str(completion_path), bashrc_updated=updated, notes=notes)
