from __future__ import annotations

import os
import shutil
from pathlib import Path

from acpw.types import InstallResponse, UninstallResponse

MARKER = "# acpw bash completion"
COMPLETION_DIR = Path.home() / ".local" / "share" / "bash-completion" / "completions"


def _completion_script() -> str:
    return """# acpw — generated by `acpw install`
_acpw_completion() {
  local IFS=$'\\n'
  local completions
  completions="$(COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD="${COMP_CWORD}" _ACPW_COMPLETE=complete-bash acpw 2>/dev/null)"
  if test -n "${completions}"; then
    COMPREPLY=( $(compgen -W "${completions}" -- "${COMP_WORDS[COMP_CWORD]}") )
  fi
}
complete -o default -F _acpw_completion acpw
"""


def install_shell() -> InstallResponse:
    notes: list[str] = []
    acpw = shutil.which("acpw")
    if not acpw:
        notes.append("acpw not on PATH; run: uv tool install --editable <this-repo>")
    COMPLETION_DIR.mkdir(parents=True, exist_ok=True)
    completion_path = COMPLETION_DIR / "acpw"
    completion_path.write_text(_completion_script(), encoding="utf-8")
    bashrc = Path.home() / ".bashrc"
    updated = False
    line = f'[ -f "{completion_path}" ] && . "{completion_path}"'
    existing = bashrc.read_text(encoding="utf-8") if bashrc.exists() else ""
    if MARKER not in existing:
        with bashrc.open("a", encoding="utf-8") as fh:
            fh.write(f"\n{MARKER}\n{line}\n")
        updated = True
        notes.append(f"appended {MARKER} to ~/.bashrc; open a new shell")
    local_bin = str(Path.home() / ".local" / "bin")
    path = os.environ.get("PATH", "")
    if local_bin not in path.split(":"):
        notes.append(f"add {local_bin} to PATH")
    return InstallResponse(
        acpw=acpw, completion=str(completion_path), bashrc_updated=updated, notes=notes
    )


def strip_bashrc_marker(text: str) -> str:
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    i = 0
    while i < len(lines):
        if lines[i].strip() == MARKER:
            i += 1
            if i < len(lines) and "bash-completion/completions/acpw" in lines[i]:
                i += 1
            if i < len(lines) and lines[i].strip() == "":
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "".join(out)


def uninstall_shell(*, purge: bool = False) -> UninstallResponse:
    notes: list[str] = []
    completion_path = COMPLETION_DIR / "acpw"
    completion_removed = False
    if completion_path.exists():
        completion_path.unlink()
        completion_removed = True
    bashrc = Path.home() / ".bashrc"
    bashrc_updated = False
    if bashrc.exists():
        original = bashrc.read_text(encoding="utf-8")
        stripped = strip_bashrc_marker(original)
        if stripped != original:
            bashrc.write_text(stripped, encoding="utf-8")
            bashrc_updated = True
    purged = False
    if purge:
        from acpw.paths import config_dir, state_dir
        from acpw.registry import load_registry
        from acpw.service import stop

        for name in list(load_registry().workers):
            stop(name)
        for path in (config_dir(), state_dir()):
            if path.exists():
                shutil.rmtree(path)
        purged = True
        notes.append("removed ~/.config/acp-workers and ~/.local/state/acp-workers")
    notes.append("CLI still on PATH until: uv tool uninstall acpw")
    notes.append(
        "skill symlink: rm ~/.agents/skills/acp-workers  (or npx skills remove acp-workers -g)"
    )
    return UninstallResponse(
        completion_removed=completion_removed,
        bashrc_updated=bashrc_updated,
        purged=purged,
        notes=notes,
    )
